apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: datavolumes.com.github.jw3
spec:
  group: com.github.jw3
  names:
    kind: DataVolume
    listKind: DataVolumeList
    plural: datavolumes
    singular: datavolume
  scope: Namespaced
#
# the status will not updatewithout removing the following
# https://github.com/fabric8io/kubernetes-client/issues/1548#issuecomment-495598904
#  subresources:
#    status: {}
#
  validation:
    openAPIV3Schema:
      description: DataVolume is the Schema for the datavolumes API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DataVolumeSpec defines the desired state of DataVolume
          type: object
        status:
          description: DataVolumeStatus defines the observed state of DataVolume
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
